spring:
  application:
    name: springboard
  profiles:
    include:
      - local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
